
ALTER TABLE INFORMACION_PERSONAL ADD CONSTRAINT CK_CORREO_INFORMACION_PERSONAL CHECK(correo NOT LIKE '%@%@%');

ALTER TABLE REFERENCIA ADD CONSTRAINT CK_CORREO_REFERENCIA CHECK(correo NOT LIKE '%@%@%');

ALTER TABLE LIBRO ADD CONSTRAINT CK_N_PAGE CHECK(numero_paginas>1);

ALTER TABLE LIBRO ADD CONSTRAINT CK_N_DIS CHECK(disponible>=0);

ALTER TABLE LIBRO ADD CONSTRAINT CK_N_EJEMPLARES CHECK(numero_ejemplares>0);



