CREATE OR REPLACE PACKAGE PK_CLIENTE IS
	PROCEDURE AD_CLIENTE (xcodigo IN VARCHAR, xnombre IN VARCHAR, xtel IN VARCHAR);
	FUNCTION CO_CLIENTE return sys_refcursor;
	PROCEDURE AD_INFORMACION_PERSONAL (xcodigo IN VARCHAR,xdireccion IN VARCHAR, xtelefono IN NUMBER, xcorreo IN VARCHAR, xcarrera_profesional IN VARCHAR);
	FUNCTION CO_INFORMACION_PERSONAL return sys_refcursor;
	PROCEDURE MO_INFORMACION_PERSONAL (xdireccion IN VARCHAR, xtelefono IN NUMBER, xcorreo IN VARCHAR);
	PROCEDURE AD_REFERENCIA (xcodigo IN VARCHAR, xnombre IN VARCHAR, xdireccion IN VARCHAR, xtelefono IN NUMBER, xcorreo IN VARCHAR);
	FUNCTION CO_REFERENCIA return sys_refcursor;
	PROCEDURE MO_REFERENCIA (xdireccion IN VARCHAR, xtelefono IN NUMBER, xcorreo IN NUMBER);
END PK_CLIENTE;
/
CREATE OR REPLACE PACKAGE PK_USUARIO IS
	PROCEDURE AD_USUARIO (xnombre IN VARCHAR, xtel IN VARCHAR);
	FUNCTION CO_USUARIO return sys_refcursor;
	PROCEDURE MO_USUARIO (xtel IN VARCHAR);
END PK_USUARIO;
/
CREATE OR REPLACE PACKAGE PK_AUTOR IS
	PROCEDURE AD_AUTOR (xnombre IN VARCHAR, xciudad IN VARCHAR,xpais IN NUMBER, xcod_libro IN VARCHAR);
	FUNCTION CO_AUTOR return sys_refcursor;
END PK_AUTOR;
/
CREATE OR REPLACE PACKAGE PK_COMPRA IS
	PROCEDURE AD_COMPRA (xcodigo IN VARCHAR, xprecio IN VARCHAR, xcog_libro IN NUMBER, xdescuento IN VARCHAR, xcliente IN VARCHAR);
	FUNCTION CO_COMPRA return sys_refcursor;
END PK_COMPRA;
/
CREATE OR REPLACE PACKAGE PK_EDITORIAL IS
	PROCEDURE AD_EDITORIAL (xcodigo IN VARCHAR, xnombre IN VARCHAR, xtelefono IN NUMBER, xdireccion IN VARCHAR, xcorreo IN VARCHAR);
	FUNCTION CO_EDITORIAL return sys_refcursor;
	PROCEDURE MO_EDITORIAL (xdireccion IN VARCHAR, xtelefono IN NUMBER, xcorreo IN VARCHAR);
END PK_EDITORIAL;
/
CREATE OR REPLACE PACKAGE PK_LIBRO IS
	PROCEDURE AD_LIBRO (xisbn IN VARCHAR, xtitulo IN VARCHAR, num_pag IN NUMBER, xnum_ejemplares IN NUMBER, xdisponibles IN NUMBER);
	FUNCTION CO_LIBRO return sys_refcursor;
END PK_LIBRO;

insert into Compra  values ('Lanceleaf Blanketflower', '$2.13B', 9461, 4.9,10);
EXECUTE PK_COMPRA.AD_COMPRA  ('HAMLET', '$10.000', '7732', '10',2);
