CREATE OR REPLACE PACKAGE BODY PA_PERFIL IS
    FUNCTION CO_CANDIDATO RETURN SYS_REFCURSOR IS CANDIDATO SYS_REFCURSOR;
    BEGIN
	CANDIDATO := PC_OPINION.CO_CONTENIDO;
	RETURN CANDIDATO;
    END;
    
    PROCEDURE AD_CONTENIDO (xnombre IN VARCHAR,xfecha IN DATE,xtipo IN VARCHAR, xurl IN VARCHAR) IS
    BEGIN
        PC_CONTENIDO.AD_CONTENIDO (xnombre,xfecha ,xtipo , xurl);
    END;
    
    PROCEDURE AD_OPINION (xnumero IN NUMBER, xfecha IN DATE, xtipo IN VARCHAR, xjustificacion IN VARCHAR, xdetalle IN VARCHAR, xperfil IN VARCHAR, xcontenido IN VARCHAR) IS
    BEGIN
        PC_OPINION.AD_OPINION (xnumero, xfecha , xtipo , xjustificacion , xdetalle , xperfil , xcontenido);
    END;
    
    PROCEDURE AD_TEMPORAL (xduracion IN NUMBER, xidioma IN CHAR, xnombre IN VARCHAR) IS
    BEGIN
        PC_CONTENIDO.AD_TEMPORAL (xduracion, xidioma , xnombre);
    END;  
END PA_PERFIL;

CREATE OR REPLACE PACKAGE BODY PA_AUDITOR IS  
  FUNCTION CO_AUDITOR RETURN SYS_REFCURSOR IS AUDITOR SYS_REFCURSOR;
  BEGIN
	AUDITOR := PC_CONTENIDO.CO_AUDITOR;
	RETURN AUDITOR;
  END;
END PA_AUDITOR;