ALTER TABLE Contenido 
ADD CONSTRAINT CK_Contenido1 CHECK(tipo IN('F','V','A'));

ALTER TABLE Opinion 
ADD CONSTRAINT CK_Opinion1 CHECK(tipo IN('E','G','C','e N'));

ALTER TABLE Trata 
ADD CONSTRAINT CK_Trata1 CHECK(nivel IN('E','P','A'));

ALTER TABLE Temporal 
ADD CONSTRAINT CK_Temporal1 CHECK(idioma IN('E','I','F'));

ALTER TABLE Contenido 
ADD CONSTRAINT CK_Contenido2 CHECK(url LIKE('%.%.%'));

ALTER TABLE Perfil 
ADD CONSTRAINT CK_PERFIL_CORREO CHECK(correo NOT LIKE ('%@%@%') AND correo LIKE('%@%'));

ALTER TABLE Trata 
ADD CONSTRAINT CK_TRATA_PORCENTAJE CHECK(porcentaje BETWEEN 0 AND 100);

ALTER TABLE Temporal
ADD CONSTRAINT CK_TEMPORAL_DURACION CHECK(duracion BETWEEN 0 AND 180);