CREATE OR REPLACE PACKAGE PC_CONTENIDOS IS
	PROCEDURE AD_CONTENIDO (xnombre IN VARCHAR,xfecha IN DATE,xtipo IN CHAR, xurl IN VARCHAR);
    PROCEDURE AD_TEMPORAL (xduracion IN NUMBER, xidioma IN CHAR, xnombre IN VARCHAR);
	PROCEDURE MO_CONTENIDO (xurl IN VARCHAR);
	FUNCTION CO_TEMPORAL RETURN SYS_REFCURSOR;
    FUNCTION CO_CONTENIDO RETURN SYS_REFCURSOR;
END PC_CONTENIDOS;

CREATE OR REPLACE PACKAGE PC_opinion IS
	PROCEDURE AD_OPINION (xnumero IN NUMBER, xfecha IN DATE, xtipo IN VARCHAR, xjustificacion IN VARCHAR, xdetalle IN VARCHAR, xperfil IN VARCHAR, xcontenido IN VARCHAR);
	PROCEDURE MO_OPINION (xtipo IN VARCHAR, xdetalle IN VARCHAR);
	FUNCTION CO_OPINION RETURN SYS_REFCURSOR;
END PC_opinion;
